name: CI

on:
  push:
    branches:
      - feature/**
      - hotfix/**

    pull_request:
      branches:
        - develop

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet test -c Release --no-build